from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent

KNOWN = {
    "byzantines": {
        "Geórgios": "乔治奥斯",
        "Léon": "莱昂",
        "Nikifóros": "尼基福罗斯",
        "Eftókios": "埃夫托基奥斯",
        "Dimítrios": "迪米特里奥斯",
        "Fílippos": "菲利波斯",
        "Sokrátis": "索克拉提斯",
        "Pláton": "柏拉图",
        "Aléxandros": "亚历山大罗斯",
        "Lízas": "利扎斯",
        "Ilías": "伊利亚斯",
        "Íkaros": "伊卡罗斯",
        "Thiséas": "提塞阿斯",
        "Odysséas": "奥迪赛阿斯",
        "Aigás": "艾加斯",
        "Iasónas": "伊阿松纳斯",
        "Achilléas": "阿基勒亚斯",
        "Menélaos": "墨涅拉俄斯",
        "Ioánnis": "约安尼斯",
        "Ílios": "伊利奥斯",
        "Giánnis": "吉安尼斯",
        "Dimosténes": "狄摩西尼",
        "Krateós": "克拉泰奥斯",
        "Amfíon": "安菲翁",
        "Aléxios": "亚历克西奥斯",
        "Anastásios": "阿纳斯塔西奥斯",
        "Andrónikos": "安德罗尼科斯",
        "Antónios": "安东尼奥斯",
        "Arkádios": "阿卡迪奥斯",
        "Aréthas": "阿雷塔斯",
        "Menoú": "梅诺乌",
        "Vasíleios": "瓦西里奥斯",
        "Belisários": "贝利萨里奥斯",
        "Konstantínos": "康斯坦丁诺斯",
        "Ntamián": "恩塔米安",
        "Dioklítes": "迪奥克利特斯",
        "Efstáthios": "埃夫斯塔西奥斯",
        "Efthýmios": "埃夫提米奥斯",
        "Ierákleios": "伊拉克利奥斯",
        "Dáfni": "达菲尼",
        "Danái": "达奈",
        "Mídeia": "米迪亚",
        "Élena": "海伦娜",
        "Neféli": "尼菲莉",
        "Efforía": "埃福里亚",
        "Ariádni": "阿里阿德尼",
        "Alkmene": "阿尔克梅涅",
        "Evrydíki": "埃夫里迪基",
        "Olympía": "奥林匹亚",
        "Kassándra": "卡桑德拉",
        "Athiná": "雅典娜",
        "Ártemis": "阿尔忒弥斯",
        "Artemisisa": "阿尔忒米西莎",
        "Estía": "赫斯提亚",
        "Antigóni": "安提戈尼",
        "Alexándra": "亚历山德拉",
        "Tháleia": "塔勒娅",
        "Níki": "尼基",
        "Evgenía": "叶夫根尼娅",
        "Ifigéneia": "伊菲格妮娅",
        "Ismíni": "伊斯米尼",
        "Xenía": "泽尼娅",
        "Nikifóra": "尼基福拉",
        "Athanasía": "阿塔纳西娅",
        "Antonína": "安东尼娜",
        "Marína": "玛丽娜",
        "María": "玛丽亚",
        "Theodóra": "西奥多拉",
        "Aikateríni": "艾卡特丽妮",
        "Christína": "克里斯蒂娜",
        "Anastasía": "阿纳斯塔西娅",
        "Ánna": "安娜",
        "Konstantína": "康斯坦丁娜",
        "Evdokía": "伊夫多基娅",
        "Eiríni": "艾里尼",
        "Ioánnina": "约安妮娜",
        "Sofía": "索菲娅",
        "Thékla": "泰克拉",
        "Zoí": "佐伊",
        "Sára": "萨拉",
        "Vasilikí": "瓦西莉基",
        "Vasilína": "瓦西琳娜",
        "Kýra": "基拉",
        "Georgía": "乔治娅",
        "Agápi": "阿加皮",
        "Tabitha": "塔比莎",
        "Theodosía": "西奥多西亚",
        "Áriel": "艾丽尔",
        "Ráchil": "拉基尔",
        "Tsána": "察纳",
        "Filopónos": "菲洛波诺斯",
        "Monachos": "莫纳科斯",
        "Kínnamos": "基纳莫斯",
        "Mosópoulos": "莫索普洛斯",
        "Kráikos": "克拉伊科斯",
        "Xénos": "泽诺斯",
        "Galánis": "加拉尼斯",
        "Kantáke": "坎塔凯",
        "Péleos": "佩勒奥斯",
        "Achilléfs": "阿基勒夫斯",
        "Dímitra": "迪米特拉",
        "Eileithía": "艾勒提亚",
        "Evdoxía": "伊夫多克西亚",
        "Sofronía": "索弗罗尼娅",
        "Ligeía": "利盖娅",
        "Pantagióta": "潘塔吉奥塔",
        "Réa": "瑞亚",
        "Christópoulos": "克里斯托普洛斯",
        "Aarónios": "阿罗尼奥斯",
        "Apokokákos": "阿波科卡科斯",
        "Argyrós": "阿尔吉罗斯",
        "Arianítes": "阿里亚尼特斯",
        "Astynomía": "阿斯图诺米亚",
        "Vasilikés": "瓦西利凯斯",
        "Choúmnos": "丘姆诺斯",
        "Chalkokondýles": "查尔科孔迪莱斯",
        "Daimonoaniánes": "戴莫诺阿尼亚内斯",
        "Ntalásenos": "恩塔拉塞诺斯",
        "Diogénis": "狄奥根尼斯",
        "Doúkas": "杜卡斯",
        "Nkámpras": "恩坎普拉斯",
        "Nklámpas": "恩克兰帕斯",
        "Agiotheodorítes": "阿吉奥西奥多里特斯",
        "Kampalários": "坎帕拉里奥斯",
        "Kampasílas": "坎帕西拉斯",
        "Kallérgis": "卡勒吉斯",
        "Kalothétos": "卡洛塞托斯",
        "Kamateró": "卡马泰罗",
        "Kamýtzes": "卡米特泽斯",
        "Kastamonítes": "卡斯塔莫尼特斯",
        "Katakálon": "卡塔卡隆",
        "Keroulários": "凯鲁拉里奥斯",
        "Kontóstavlos": "孔托斯塔夫洛斯",
        "Kontostéfanos": "孔托斯特法诺斯",
        "Kourkoúas": "库尔库阿斯",
        "Kourtíou": "库尔提乌",
        "Makrampelítes": "马克兰佩利特斯",
        "Maleḯnos": "马雷诺斯",
        "Maliasenos": "马利亚塞诺斯",
        "Mavrogénis": "马夫罗吉尼斯",
        "Melíssenos": "梅利塞诺斯",
        "Mesopotamítes": "梅索波塔米特斯",
        "Metochítes": "梅托奇特斯",
        "Monomáchos": "莫诺马科斯",
        "Mouroúzis": "穆鲁齐斯",
        "Mouzálona": "穆扎洛纳",
        "Mouzáka": "穆扎卡",
        "Parsakouténos": "帕萨库特诺斯",
        "Petralífa": "佩特拉利法",
        "Fils": "菲尔斯",
        "Fokás": "福卡斯",
        "Ran'nkámpe": "兰坎佩",
        "Raoúl": "拉乌尔",
        "Rotzérios": "罗泽里奥斯",
        "Skléros": "斯克勒罗斯",
        "Sphrantzes": "斯弗兰策斯",
        "Synádenos": "西纳德诺斯",
        "Tankarí": "坦卡里",
        "Tarachaniótes": "塔拉查尼奥特斯",
        "Taronítes": "塔罗尼特斯",
        "Torníkios": "托尼基奥斯",
        "Tzamplákon": "兹姆普拉孔",
        "Vatátzes": "瓦塔泽斯",
        "Komninós": "科姆尼诺斯",
        "Makedoniká": "马其顿卡",
        "Palaiológos": "帕莱奥洛格斯",
        "Irákleios": "伊拉克利奥斯",
    },
    "indian": {
        "Ravi": "拉维",
        "Rajiv": "拉吉夫",
        "Santosh": "桑托什",
        "Akash": "阿卡什",
        "Akhil": "阿希尔",
        "Raj": "拉杰",
        "Rahul": "拉胡尔",
        "Rohit": "罗希特",
        "Laxman": "拉克什曼",
        "Gopal": "戈帕尔",
        "Vishnu": "毗湿奴",
        "Ashok": "阿肖克",
        "Akshay": "阿克夏",
        "Chetan": "切坦",
        "Dilip": "迪利普",
        "Deepak": "迪帕克",
        "Govind": "戈文德",
        "Hari": "哈里",
        "Harsh": "哈尔什",
        "Kamal": "卡马尔",
        "Madhav": "马达夫",
        "Sinha": "辛哈",
        "Kuwar": "库瓦尔",
        "Mishra": "米什拉",
        "Pandey": "潘代",
        "Jha": "贾",
        "Khatri": "卡特里",
        "Abha": "阿布哈",
        "Aditi": "阿迪蒂",
        "Deepti": "迪普蒂",
        "Manasi": "马纳西",
        "Jyoti": "乔提",
        "Shobhana": "绍布哈娜",
        "Shobha": "绍巴",
        "Akhila": "阿基拉",
        "Amrita": "阿姆利塔",
        "Anjali": "安加丽",
        "Anupama": "阿努帕玛",
        "Aparajita": "阿帕拉吉塔",
        "Shalini": "沙利尼",
        "Soumya": "索姆雅",
        "Lavanya": "拉万雅",
    },
    "inuits": {
        "Annakpok": "安纳克波克",
        "Kappiataitok": "卡皮亚泰托克",
        "Sangilak": "桑吉拉克",
        "Maniitok": "马尼托克",
        "Atka": "阿特卡",
        "Akluitok": "阿克鲁伊托克",
        "Aixijiq": "艾希吉克",
        "Uumaruq": "乌马鲁克",
        "Auma": "奥马",
        "Ieuuniaqtuq": "伊乌尼亚克图克",
        "Tunusisaq": "图努西萨克",
        "Sitxiq": "西特西克",
        "Siqquqtuq": "西库图克",
        "Qasigiaq": "卡西吉亚克",
        "Kiksraq": "基克斯拉克",
        "Nunafiak": "努纳菲亚克",
        "Urgiixik": "乌尔吉西克",
        "Ninfuq": "尼恩福克",
        "Qubliaqtuq": "奎布利亚克图克",
        "Kanigruaq": "卡尼格鲁阿克",
        "Ikkiq": "伊基克",
        "Sanlubuvik": "桑鲁布维克",
        "Abviq": "阿布维克",
        "Nunuqsibiixaq": "努努克西比克萨克",
        "Kanayuq": "卡纳尤克",
        "Qiviaqtuq": "奇维亚克图克",
        "Tukkaq": "图卡克",
        "Kirima": "基里马",
        "Fraixiuqtuq": "弗莱西乌克图克",
        "Ania": "阿尼亚",
        "Mauyaq": "毛雅克",
        "Nutabaq": "努塔巴克",
        "Qiqsruqaq": "奇克斯鲁克阿克",
        "Niefiqsimaruq": "尼菲克西马鲁克",
        "Apigaa": "阿皮加",
        "Apun": "阿蓬",
        "Qayuqjaq": "卡尤克雅克",
        "Tagluk": "塔格鲁克",
        "Ukpik": "乌克皮克",
        "Mavsa": "马夫萨",
        "Mapsaq": "马普萨克",
        "Aniuvak": "阿纽瓦克",
    },
    "japanese": {
        "Akira": "昭",
        "Eiichi": "英一",
        "Entarou": "圆太郎",
        "Gaku": "学",
        "Gojirou": "五次郎",
        "Hachitarou": "八太郎",
        "Hajime": "一",
        "Haruki": "春树",
        "Hideki": "秀树",
        "Hiro": "宏",
        "Hitoshi": "仁",
        "Ichirou": "一郎",
        "Itsuo": "一男",
        "Jin": "仁",
        "Kenichi": "健一",
        "Kentaro": "健太郎",
        "Mineo": "峰男",
        "Mitsuru": "充",
        "Noato": "直人",
        "Osamu": "修",
        "Reijiro": "礼次郎",
        "Renzo": "连藏",
        "Saburo": "三郎",
        "Shingo": "真吾",
        "Shinjiro": "新次郎",
        "Shinya": "真也",
        "Shouji": "章司",
        "Tadashi": "忠",
        "Takuji": "拓治",
        "Tai": "太",
        "Toyotomi": "丰臣",
        "Tsuyoshi": "刚",
        "Yuichiro": "雄一郎",
        "Yuijiro": "祐次郎",
    },
    "mayan": {
        "Yax": "雅克",
        "Pasaj": "帕萨克",
        "Chan": "昌",
        "Yoaat": "约阿特",
        "Ukit": "乌基特",
        "Took'": "图克",
        "K'inich": "基尼奇",
        "K'uk'": "库克",
        "Mo'": "莫",
        "K'u": "库",
        "Ix": "伊克斯",
        "B'alam": "巴拉姆",
        "Nan": "南",
        "Imix": "伊米克斯",
        "K'awiil": "卡维尔",
        "Waxaklajuun": "瓦沙克拉胡恩",
        "Ub'aah": "乌巴赫",
    },
    "norman": {
        "Waldemar": "瓦尔德马",
        "Vilfrid": "维尔弗里德",
        "Thorstein": "托尔斯坦",
        "Tankred": "坦克雷德",
        "Svenning": "斯文宁",
        "Sigvald": "西格瓦尔德",
        "Sigmar": "西格马",
        "Roland": "罗兰",
        "Reginald": "雷金纳德",
        "Radulf": "拉杜夫",
        "Otvard": "奥特瓦德",
        "Odomar": "奥多马",
        "Norbert": "诺伯特",
        "Manfred": "曼弗雷德",
        "Lothar": "洛塔尔",
        "Lambert": "兰伯特",
        "Klothar": "克洛塔尔",
        "Ingmar": "英格马",
        "Hubert": "于贝尔",
        "Gildwin": "吉尔德温",
        "Gervin": "格尔文",
        "Gerald": "格拉尔德",
        "Froward": "弗罗沃德",
        "Fredegar": "弗雷德加",
        "Falko": "法尔科",
        "Elfride": "埃尔弗里德",
        "Erwin": "埃尔温",
        "Ditmar": "迪特马",
        "Didrik": "迪德里克",
        "Bernhard": "贝恩哈德",
        "Answald": "安斯瓦尔德",
        "Adalrik": "阿达尔里克",
    },
    "seljuk": {
        "Yunus": "尤努斯",
        "Selim": "塞利姆",
        "Murat": "穆拉特",
        "Bekir": "贝基尔",
        "Ali": "阿里",
        "Osman": "奥斯曼",
        "Hamdi": "哈姆迪",
        "Hüseyin": "胡赛因",
        "Emre": "埃姆雷",
        "Oğuzhan": "奥古兹汗",
        "Ertuğrul": "埃尔图鲁尔",
        "Abdullah": "阿卜杜拉",
        "Ahmet": "艾哈迈德",
        "Mehmet": "梅赫梅特",
        "Orhan": "奥尔汗",
        "Ramazan": "拉马赞",
        "Yasin": "亚辛",
        "Hamza": "哈姆扎",
        "Mahmut": "马哈穆特",
        "Muhammet": "穆罕默德",
        "Salih": "萨利赫",
        "Furkan": "富尔坎",
        "Recep": "雷杰普",
        "Yusuf": "优素福",
        "Hasan": "哈桑",
        "Ibrahim": "易卜拉欣",
        "Ismail": "伊斯梅尔",
        "Mustafa": "穆斯塔法",
        "Süleyman": "苏莱曼",
        "Adem": "阿德姆",
        "Ömer": "奥马尔",
        "Omar": "奥马尔",
        "Kerem": "凯雷姆",
        "Enes": "埃内斯",
        "Umut": "乌穆特",
    },
}


def normalize_text(text: str) -> str:
    text = text.strip()
    text = text.replace("’", "'").replace("`", "")
    text = re.sub(r"[\u0300-\u036f]", "", text)
    text = text.replace("-", "")
    return text


def translit(text: str) -> str:
    text = normalize_text(text)
    if not text:
        return ""
    s = text.lower()
    for src, dst in [
        ("th", "特"), ("ph", "弗"), ("ch", "克"), ("sh", "什"), ("kh", "赫"), ("ks", "克斯"),
        ("ps", "普斯"), ("ou", "欧"), ("ei", "艾"), ("ai", "艾"), ("au", "奥"), ("eu", "尤"),
        ("ia", "亚"), ("io", "约"), ("ie", "耶"), ("oi", "奥伊"), ("ua", "瓦"), ("ue", "维"),
        ("ui", "维"), ("oo", "奥"), ("ee", "伊"), ("yo", "约"), ("yu", "尤"), ("ya", "雅"),
    ]:
        s = s.replace(src, dst)
    mapping = {
        'a': '阿', 'e': '埃', 'i': '伊', 'o': '奥', 'u': '乌', 'y': '伊',
        'b': '布', 'p': '普', 'd': '德', 't': '特', 'k': '克', 'g': '格', 'f': '弗',
        'h': '赫', 'j': '杰', 'q': '库', 'c': '西', 's': '斯', 'r': '尔', 'l': '尔',
        'm': '姆', 'n': '恩', 'v': '维', 'w': '威', 'x': '克斯', 'z': '泽',
    }
    out = []
    for char in s:
        if char.isalpha():
            out.append(mapping.get(char, char))
        else:
            out.append(char)
    return "".join(out)


def translate_line(text: str, culture: str) -> tuple[str, bool]:
    norm = normalize_text(text)
    if not norm:
        return "", False
    culture_map = KNOWN.get(culture, {})
    if norm in culture_map:
        return culture_map[norm], True
    if norm.lower() in culture_map:
        return culture_map[norm.lower()], True
    return translit(norm), False


notes = []
for path in sorted(ROOT.glob("*/namelists/*.txt")):
    rel = path.relative_to(ROOT).as_posix()
    culture = rel.split("/")[0]
    lines = path.read_text(encoding="utf-8").splitlines()
    translated = []
    uncertain = []
    for line in lines:
        if not line.strip():
            translated.append("")
            continue
        out, is_known = translate_line(line, culture)
        translated.append(out)
        if not is_known:
            uncertain.append(line.strip())
    path.write_text("\n".join(translated) + ("\n" if translated else ""), encoding="utf-8")
    if uncertain:
        sample = uncertain[:8]
        notes.append(f"- {rel}: {len(uncertain)} 项使用自动音译，示例：{', '.join(sample)}")

notes_path = ROOT / "translation_notes.md"
text = notes_path.read_text(encoding="utf-8")
appendix = "\n\n## 已处理文件\n"
appendix += "\n".join(notes) + "\n"
notes_path.write_text(text + appendix, encoding="utf-8")
print(f"translated files: {len(list(ROOT.glob('*/namelists/*.txt')))}")
print("done")
