#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Aug 18 09:05:31 CST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Bliss_v2.1.2_(Chocapic13_Shaders_edit).zip
